### ISSUE TITLE
I dont understand why we do this to image 

### ISSUE THREAD

**Issue by Naba7** [udacity/deep-learning-v2-pytorch#104]
image = image.transpose(1,2,0)
    image = image * np.array((0.229, 0.224, 0.225)) + np.array((0.485, 0.456, 0.406))
    image = image.clip(0, 1)

**Comment by iamRusty** [comment]
@Naba7 Hi! 
The original image tensor has a dimension [b, C, H, W], where `b`, is the batch size. `C` is the number of channels, `H` is the height and `W` is the width. I am assuming that the original image is first through a squeeze() function; removing the first dimension and leaving us with a tensor of dimension [C, H, W]. 

Unfortunately, matplotlib's imshow() function is strict with the image dimension and shape. It only accepts numpy array with values in the range of [0, 1], hence the use `clip()` function. Also, imshow() expects an image with dimension [H,W,C], that's why we tranpose() function was used. Finally, the original image tensor was preprocessed/normalized. To unnormalize the resulting image array, we multiply it by the previous standard deviation and add the means of each channel.
