### ISSUE TITLE
Unclear sentence in Character_Level_RNN_Exercise.ipynb

### ISSUE THREAD

**Issue by JulianMich00** [udacity/deep-learning-v2-pytorch#127]
"The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute)" I believe there is a typo here in "err"

**Comment by jchernus** [comment]
Here, to 'err' is to 'lean towards'. The sentence is suggesting that if you can, make your network larger rather than smaller, and you'll be more likely to have a successful result. 

I agree that it's not the ideal way to phrase it. If you're willing to submit a pull request with alternate wording, I'll happily accept!
